### ISSUE TITLE
Testing and predicting with TENER

### ISSUE THREAD

**Issue by 7228TigersFan** [fastnlp/TENER#20] opened 2020-07-20 11:28 UTC
Hello, first and foremost I hope this message finds you well and healthy. I need to load the model and test it on specific data. The data type is str. Can you please send me the demo? Thank you. 
I look forward to your reply.
Sincerely,

**Comment by yhcc** [comment] 2020-07-22 04:56
Duplicate of #14

**Closed as completed** 2020-07-23 11:41 UTC
